server:
  port: 8080

spring:
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  application:
    name: api-service
  datasource:
    driver-class-name: org.postgresql.Driver
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer