services:
  kafka:
    image: confluentinc/cp-kafka:8.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: retro_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Retro

  db-service:
    container_name: db-service
    build:
      context: ./db-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/Retro
      - DB_USERNAME=retro_user
      - DB_PASSWORD=12345
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROFILE_ACTIVE=prod
    depends_on:
      - db
      - kafka

  api-service:
    container_name: api-service
    build:
      context: ./api-service
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/Retro
      - DB_USERNAME=retro_user
      - DB_PASSWORD=12345
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROFILE_ACTIVE=prod
    depends_on:
      - db
      - kafka
      - db-service