services:
  kafka:
    container_name: kafka-container
    image: apache/kafka
    ports:
      - "9092:9092"
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: retro_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Retro

  db-service:
    container_name: db-service
    image: db-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/Retro
      - DB_USERNAME=retro_user
      - DB_PASSWORD=12345
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROFILE_ACTIVE=prod
    depends_on:
      - db
      - kafka

  api-service:
    container_name: api-service
    image: api-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/Retro
      - DB_USERNAME=retro_user
      - DB_PASSWORD=12345
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PROFILE_ACTIVE=prod
    depends_on:
      - db
      - kafka
      - db-service