spring:
  application:
    name: db-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/Retro}
    username: ${DB_USERNAME:retro_user}
    password: ${DB_PASSWORD:12345}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

logging:
  level:
    root: INFO
